default:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

variables:
  REGISTRY_HOME: "${CI_REGISTRY}/${CI_PROJECT_PATH}/"
  CI_DEBUG_TRACE: "true"

cache:
  paths:
    - .cache/pip
    - .cache/kaniko
    - /kaniko

stages:
  - build-image

before_script:
  - mkdir -p /kaniko/.docker
  # adding our cert to kaniko's additional certs
  - cat ${CI_SERVER_TLS_CA_FILE} >> /kaniko/ssl/certs/additional-ca-cert-bundle.crt
  # Creating kaniko config
  - >
    echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" 
    | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

chem-util-build:
  stage: build-image
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/images/molecules/"
      --dockerfile "${CI_PROJECT_DIR}/images/molecules/Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/chem-util:latest"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/chem-util:${CI_COMMIT_SHORT_SHA}"

  rules:
    - changes:
        - images/molecules/**/*


pytorch-mnist-build:
  stage: build-image
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/images/pytorch-lightning-mnist-image/"
      --dockerfile "${CI_PROJECT_DIR}/images/pytorch-lightning-mnist-image/Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/pytorch-lightning-mnist-training:latest"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/pytorch-lightning-mnist-training:commit-${CI_COMMIT_SHORT_SHA}"

  rules:
    - changes:
        - images/pytorch-lightning-mnist-image/**/*
