apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mamba-130m-hf-inf-serv
  namespace: kubeflow-user-example-com
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=mamba-130m-hf-model-name
        - --model_id=state-spaces/mamba-130m-hf
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 4Gi
          nvidia.com/gpu: "1"
