apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-inf-serv
  namespace: kubeflow-user-example-com
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=qwen-model-name
        - --model_id=Qwen/Qwen2.5-1.5B-Instruct
      resources:
        limits:
          cpu: "8"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 4Gi
          nvidia.com/gpu: "1"
