apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-1-5b
  namespace: kubeflow-user-example-com
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-1-5b
  namespace: kubeflow-user-example-com
  labels:
    app: qwen-1-5b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-1-5b
  template:
    metadata:
      labels:
        app: qwen-1-5b
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: qwen-1-5b
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: qwen-1-5b
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: ["vllm serve Qwen/Qwen2.5-1.5B-Instruct --trust-remote-code --enable-chunked-prefill --max_num_batched_tokens 1024 --dtype=half"]
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "8"
            memory: 16Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-1-5b
  namespace: kubeflow-user-example-com
spec:
  ports:
  - name: http-qwen-1-5b
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: qwen-1-5b
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-1-5b-nodeport
  namespace: kubeflow-user-example-com
spec:
  ports:
  - name: http-qwen-1-5b
    port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 32235
  selector:
    app: qwen-1-5b
  sessionAffinity: None
  type: NodePort
