apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: chem-classifier-model
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://kubeflow-examples/models/output.joblib
  transformer:
    containers:
      - image: kubeflow-examples/chem-util:e79ef6c9
        name: kserve-container
        command:
          - "/opt/conda/bin/python"
          - "/app/model-transformer.py"
          - "serve_transformer"
        args:
          - --model_name
          - chem-classifier