apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: chem-classifier
spec:
  predictor:
    containers:
      - name: sklearn-custom-container
        image: gitlab-demo.prokube.ai:4567/kiss/kubeflow-examples/chem-util:latest
        imagePullPolicy: Always
        command:
          - "/opt/conda/bin/python"
          - "/app/model-serving.py"
          - "serve_predictor"
        args:
          - --model_name
          - chem-classifier
        env:
          - name: STORAGE_URI
            value: "s3://kubeflow-examples/models/output.joblib"
          - name: MODEL_FILENAME
            value: "output.joblib"
  transformer:
    containers:
      - image: gitlab-demo.prokube.ai:4567/kiss/kubeflow-examples/chem-util:latest
        imagePullPolicy: Always
        name: transformer-container
        command:
          - "/opt/conda/bin/python"
          - "/app/model-serving.py"
          - "serve_transformer"
        args:
          - --model_name
          - chem-classifier
          - --n_bits
          - '2048'